// 🃏 The HossGame 🃏
// <copyright file="ProjectDTO.cs" company="Reactive">
// Copyright (c) Reactive. All rights reserved.
// </copyright>
// 🃏 The HossGame 🃏

using Ardalis.GuardClauses;

namespace TheHossGame.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class ProjectDto : CreateProjectDto
{
    public ProjectDto(
        int id,
        string name,
        IList<ToDoItemDto>? items = null)
        : base(name)
    {
        Guard.Against.Null(items);
        this.Id = id;
        this.Items = items.ToList() ?? new List<ToDoItemDto>();
    }

    public int Id { get; set; }

    public IList<ToDoItemDto> Items { get; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreateProjectDto
{
    protected CreateProjectDto(string name)
    {
        this.Name = name;
    }

    public string Name { get; set; }
}
