name: Deploy Pulumi
on:
  - push
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ec4df7f7-c800-4978-b3e4-8025ad316398
          tenant-id: 670ae364-91f7-4467-b703-9897c56df8e6
          subscription-id: 5c287342-053b-4a49-8a70-0ac22a40abb9 
          enable-AzPSSession: true
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
